install:
	mkdir -p $(DESTDIR)/usr/share/disable-external-gpu
	mkdir -p $(DESTDIR)/usr/share/applications
	install main.py $(DESTDIR)/usr/share/disable-external-gpu
	install main.ui $(DESTDIR)/usr/share/disable-external-gpu
	install disable-gpu.desktop $(DESTDIR)/usr/share/applications
